# Generated by Django 5.1.5 on 2025-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(max_length=255, null=True),
        ),
    ]
