# Generated by Django 5.1.5 on 2025-03-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0002_billdetails_temp_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billdetails",
            name="temp_field",
        ),
    ]
