# Generated by Django 5.1.5 on 2025-03-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0002_bill_pdf_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="pdf_path",
        ),
    ]
