# Generated by Django 5.1.5 on 2025-03-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0002_category_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="categoryID",
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
