# Generated by Django 5.1.5 on 2025-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0003_remove_bill_pdf_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Solid_grey.svg/2048px-Solid_grey.svg.png",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("categoryID", "name")},
        ),
    ]
