# Generated by Django 5.1.6 on 2025-03-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisaab', '0003_alter_category_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
