# Generated by Django 5.1.5 on 2025-03-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0004_alter_category_image_url_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.URLField(
                blank=True,
                default="https://fiveislands.scilly.sch.uk/wp-content/themes/block-theme/images/default.jpg",
                max_length=255,
                null=True,
            ),
        ),
    ]
