# Generated by Django 5.1.5 on 2025-03-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0005_remove_bill_id_remove_category_id_remove_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="customerName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
