# Generated by Django 5.1.5 on 2025-03-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hisaab", "0006_bill_customername"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="discount",
            field=models.IntegerField(
                choices=[(0, "No Discount"), (5, "5%"), (10, "10%"), (15, "15%")],
                default=5,
            ),
        ),
    ]
